# TOER Scoring Configuration

yards_per_play:
  thresholds:
    - {condition: "ypp > 5.5", score: 10}
    - {condition: "ypp >= 5.5", score: 9}
    - {condition: "ypp >= 5.45", score: 8}
    - {condition: "ypp >= 5.40", score: 7}
    - {condition: "ypp >= 5.35", score: 6}
    - {condition: "ypp >= 5.30", score: 5}
    - {condition: "ypp >= 5.25", score: 4}
    - {condition: "ypp >= 5.20", score: 3}
    - {condition: "ypp >= 5.15", score: 2}
    - {condition: "ypp >= 5.10", score: 1}
    - {condition: "default", score: 0}

turnovers:
  exact_values:
    - {value: 0, score: 10}
    - {value: 1, score: 5}
    - {value: 2, score: 0}
    - {value: 3, score: -3}
    - {value: 4, score: -4}
  default_score: -5

completion_percentage:
  thresholds:
    - {condition: "comp_pct >= 67.5", score: 10}
    - {condition: "comp_pct >= 67.0", score: 9}
    - {condition: "comp_pct >= 66.5", score: 8}
    - {condition: "comp_pct >= 66.0", score: 7}
    - {condition: "comp_pct >= 65.5", score: 6}
    - {condition: "comp_pct >= 65.0", score: 5}
    - {condition: "comp_pct >= 64.5", score: 4}
    - {condition: "comp_pct >= 64.0", score: 3}
    - {condition: "comp_pct >= 63.5", score: 2}
    - {condition: "comp_pct >= 63.0", score: 1}
    - {condition: "default", score: 0}

rush_yards_per_carry:
  thresholds:
    - {condition: "ypc >= 4.7", score: 10}
    - {condition: "ypc >= 4.65", score: 9}
    - {condition: "ypc >= 4.60", score: 8}
    - {condition: "ypc >= 4.55", score: 7}
    - {condition: "ypc >= 4.50", score: 6}
    - {condition: "ypc >= 4.45", score: 5}
    - {condition: "ypc >= 4.40", score: 4}
    - {condition: "ypc >= 4.35", score: 3}
    - {condition: "ypc >= 4.30", score: 2}
    - {condition: "ypc >= 4.20", score: 1}
    - {condition: "default", score: 0}

sacks:
  exact_values:
    - {value: 0, score: 10}
    - {value: 1, score: 8}
    - {value: 2, score: 5}
    - {value: 3, score: 0}
    - {value: 4, score: -1}
  default_score: -3

third_down_percentage:
  thresholds:
    - {condition: "third_down_pct >= 43.0", score: 10}
    - {condition: "third_down_pct >= 42.0", score: 9}
    - {condition: "third_down_pct >= 41.0", score: 8}
    - {condition: "third_down_pct >= 40.0", score: 7}
    - {condition: "third_down_pct >= 39.0", score: 6}
    - {condition: "third_down_pct >= 38.0", score: 5}
    - {condition: "third_down_pct >= 37.0", score: 4}
    - {condition: "third_down_pct >= 36.0", score: 3}
    - {condition: "third_down_pct >= 35.0", score: 2}
    - {condition: "third_down_pct >= 33.0", score: 1}
    - {condition: "default", score: 0}

success_rate:
  thresholds:
    - {condition: "success_rate >= 47.0", score: 10}
    - {condition: "success_rate >= 46.0", score: 9}
    - {condition: "success_rate >= 45.0", score: 8}
    - {condition: "success_rate >= 44.0", score: 7}
    - {condition: "success_rate >= 43.0", score: 6}
    - {condition: "success_rate >= 42.0", score: 5}
    - {condition: "success_rate >= 41.0", score: 4}
    - {condition: "success_rate >= 40.0", score: 3}
    - {condition: "default", score: 0}

first_downs:
  thresholds:
    - {condition: "first_downs >= 22", score: 10}
    - {condition: "first_downs >= 21", score: 9}
    - {condition: "first_downs >= 20", score: 8}
    - {condition: "first_downs >= 19", score: 7}
    - {condition: "first_downs >= 18", score: 6}
    - {condition: "first_downs >= 17", score: 5}
    - {condition: "default", score: 0}

points_per_drive:
  thresholds:
    - {condition: "ppd >= 2.4", score: 10}
    - {condition: "ppd >= 2.35", score: 9}
    - {condition: "ppd >= 2.30", score: 8}
    - {condition: "ppd >= 2.25", score: 7}
    - {condition: "ppd >= 2.20", score: 6}
    - {condition: "ppd >= 2.10", score: 5}
    - {condition: "ppd >= 2.00", score: 4}
    - {condition: "ppd >= 1.90", score: 3}
    - {condition: "ppd >= 1.85", score: 2}
    - {condition: "ppd >= 1.80", score: 1}
    - {condition: "default", score: 0}

redzone_td_percentage:
  thresholds:
    - {condition: "redzone_td_pct >= 63.0", score: 10}
    - {condition: "redzone_td_pct >= 61.0", score: 9}
    - {condition: "redzone_td_pct >= 60.0", score: 8}
    - {condition: "redzone_td_pct >= 59.0", score: 7}
    - {condition: "redzone_td_pct >= 58.0", score: 6}
    - {condition: "redzone_td_pct >= 57.0", score: 5}
    - {condition: "default", score: 0}

penalty_yards:
  thresholds:
    - {condition: "penalty_yards == 0", score: 5}
    - {condition: "penalty_yards <= 10", score: 3}
    - {condition: "penalty_yards <= 20", score: 1}
    - {condition: "penalty_yards <= 30", score: 0}
    - {condition: "penalty_yards <= 40", score: -2}
    - {condition: "penalty_yards <= 50", score: -4}
    - {condition: "penalty_yards <= 60", score: -5}
    - {condition: "penalty_yards <= 70", score: -6}
    - {condition: "penalty_yards <= 80", score: -8}
    - {condition: "penalty_yards <= 90", score: -9}
    - {condition: "default", score: -10}